services:
  dje-party:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd backend && node server.js"
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on: []